import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import { useEffect, useState } from "react";
import Layout, { Grid, Header, Headline, Main } from "@/src/layout/layout";
import { CardTask } from "@/src/layout/card";
import { InputNewTask } from "@/src/components/input";
import { ButtonAddTask } from "@/src/components/button";

const ENDPOINT = `http://localhost:4000/api/v1/tasks`;

export default function Home() {
  const [tasks, setTasks] = useState([]);
  const [text, setText] = useState("");

  const loadTasks = async () => {
    const res = await fetch(ENDPOINT);
    const data = await res.json();
    setTasks(data);
  };

  const addTask = async () => {
    if (!text) return;
    await fetch(ENDPOINT, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ text }),
    });
    setText("");
    loadTasks();
  };

  const onDelete = async (id) => {
    await loadTasks()
  };

  useEffect(() => {
    loadTasks();
  }, []);
  //
  return (
    <Layout>
      <Head>
        <title>To-Do List</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header>
          <Headline>
            <h1>Minhas Tarefas</h1>
          </Headline>

          <Headline>
            <InputNewTask text={text} addTask={addTask} setText={setText} />
            <ButtonAddTask addTask={addTask} />
          </Headline>
        </Header>

      <Main>
        <Grid>
          {tasks.map((task) => (
            <CardTask key={task.id} data={task} onDelete={onDelete} />
          ))}
        </Grid>
      </Main>
    </Layout>
  );
}
